### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by cradules** [MaiaRadulescu/school#1]
The code is looking great and will look even better if you will calculate the area and perimeter inside of a function and return the result.

Example:

```
def  perimeter (shape_l, shape_w):
    result = (shape_l + shape_w) * 2
return result

```

In this way, the code is cleaner and easier to understand and you can avoid some issues with stored values in memory for the future 🥇 

Later on, maybe we can move even further and create a  library for using object-oriented programing.  Same as you learn with  

```
dragon.fire or dragon.smash
```

**Comment by MaiaRadulescu** [comment]
fixed
